example_create_phone_number_response = {
    "fallbackDestination": {
        "type": "number",
        "numberE164CheckEnabled": True,
        "number": "+14155551234",
        "extension": "123",
        "message": "This is a fallback message.",
        "description": "Fallback description.",
    },
    "provider": "byo_phone_number",
    "numberE164CheckEnabled": True,
    "id": "phone-number-id-123",
    "orgId": "org-id-123",
    "createdAt": "2023-09-07T12:00:00Z",
    "updatedAt": "2023-09-07T12:30:00Z",
    "name": "Test Phone Number",
    "assistantId": "assistant-id-123",
    "squadId": "squad-id-123",
    "serverUrl": "https://server.url",
    "serverUrlSecret": "server-secret-123",
    "number": "+14155551234",
    "credentialId": "credential-id-123",
}


example_delete_phone_number_response = {
    "fallbackDestination": {
        "type": "number",
        "numberE164CheckEnabled": True,
        "number": "+14155551234",
        "extension": "123",
        "message": "Backup destination in case of failure",
        "description": "Test description for the fallback",
    },
    "provider": "byo_phone_number",
    "numberE164CheckEnabled": True,
    "id": "phone-number-id-123",
    "orgId": "org-id-456",
    "createdAt": "2023-11-07T05:31:56Z",
    "updatedAt": "2023-11-07T05:31:56Z",
    "name": "Main Office Line",
    "assistantId": "assistant-id-789",
    "squadId": "squad-id-321",
    "serverUrl": "https://example.com/server-url",
    "serverUrlSecret": "secret-key",
    "number": "+14155551234",
    "credentialId": "credential-id-654",
}


# Example usage
example_get_phone_number_response = {
    "fallbackDestination": {
        "type": "number",
        "numberE164CheckEnabled": True,
        "number": "+14155551234",
        "extension": "123",
        "message": "Fallback message in case of failure.",
        "description": "Fallback for missed calls.",
    },
    "provider": "byo_phone_number",
    "numberE164CheckEnabled": True,
    "id": "phone-number-id-123",
    "orgId": "org-id-456",
    "createdAt": "2023-11-07T05:31:56Z",
    "updatedAt": "2023-11-07T05:31:56Z",
    "name": "Test Phone Number",
    "assistantId": "assistant-id-789",
    "squadId": "squad-id-1011",
    "serverUrl": "https://example.server.url",
    "serverUrlSecret": "server-secret-123",
    "number": "+14155551234",
    "credentialId": "credential-id-456",
}

example_list_phone_numbers_response = [
    {
        "fallbackDestination": {
            "type": "number",
            "numberE164CheckEnabled": True,
            "number": "+14155551234",
            "extension": "1234",
            "message": "Fallback message",
            "description": "Fallback description",
        },
        "provider": "byo_phone_number",
        "numberE164CheckEnabled": True,
        "id": "phone-number-123",
        "orgId": "org-123",
        "createdAt": "2023-11-07T05:31:56Z",
        "updatedAt": "2023-11-07T05:31:56Z",
        "name": "Test Phone Number",
        "assistantId": "assistant-123",
        "squadId": "squad-123",
        "serverUrl": "https://my-server-url.com",
        "serverUrlSecret": "my-server-secret",
        "number": "+14155551234",
        "credentialId": "credential-123",
    },
    {
        "fallbackDestination": {
            "type": "number",
            "numberE164CheckEnabled": True,
            "number": "+14155554321",
            "extension": "5678",
            "message": "Fallback message",
            "description": "Fallback description",
        },
        "provider": "byo_phone_number",
        "numberE164CheckEnabled": True,
        "id": "phone-number-456",
        "orgId": "org-123",
        "createdAt": "2023-11-06T12:00:00Z",
        "updatedAt": "2023-11-06T12:30:00Z",
        "name": "Secondary Phone Number",
        "assistantId": "assistant-456",
        "squadId": "squad-456",
        "serverUrl": "https://my-other-server-url.com",
        "serverUrlSecret": "my-other-server-secret",
        "number": "+14155554321",
        "credentialId": "credential-456",
    },
]


example_update_phone_number_response = {
    "fallbackDestination": {
        "type": "number",
        "numberE164CheckEnabled": True,
        "number": "+14155551234",
        "extension": "1234",
        "message": "Fallback message",
        "description": "Fallback description",
    },
    "provider": "byo_phone_number",
    "numberE164CheckEnabled": True,
    "id": "phone-number-123",
    "orgId": "org-123",
    "createdAt": "2023-11-07T05:31:56Z",
    "updatedAt": "2023-11-08T05:31:56Z",
    "name": "Updated Phone Number",
    "assistantId": "assistant-123",
    "squadId": "squad-123",
    "serverUrl": "https://updated-server-url.com",
    "serverUrlSecret": "updated-secret-key",
    "number": "+14155551234",
    "credentialId": "credential-123",
}
